logback.elk.destination=localhost:5000

# SMTP server settings
spring.mail.host=mail.hospitalcayetano.gob.pe
#spring.mail.port=465
spring.mail.username=hchsigehoweb@hospitalcayetano.gob.pe
spring.mail.password=*Hch2024.*

# Additional email properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtps.quitwait=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
